### ISSUE TITLE
[Style][Components] 광고 배너 슬라이더 구현

### ISSUE THREAD

**Issue by hodin030** [AI-x-optional/FE#15]
## Description

광고 배너 슬라이더 구현

---

## TODO

- [x] swiper module 설치
- [x] 배너 컴포넌트 생성
- [x] 메인페이지에 배너 컴포넌트 적용

---

## ScreenShots

구현할 화면 및 컴포넌트의 디자인 화면을 캡쳐합니다.
![10EBDD4C-07BE-459C-A12C-462B0CE512F3_1_201_a](https://github.com/AI-x-optional/FE/assets/134986912/b0a4dca1-34f6-46e0-8471-4e64e85f61b7)

---
