### ISSUE TITLE
[Style][BootCamp] 부트캠프 상세 조회 페이지 구현

### ISSUE THREAD

**Issue by hodin030** [AI-x-optional/FE#19]
## Description

부트캠프 상세 조회 페이지 구현

---

## TODO

- [x] 부트캠프 동적 라우팅 페이지 생성
- [x] fetch API 적용
- [x] 부트캠프 상세 조회 페이지 디자인 및 구현

---

## ScreenShots

<img width="1512" alt="스크린샷 2024-05-23 오후 2 36 57" src="https://github.com/AI-x-optional/FE/assets/134986912/48baa2ec-6ad1-4c50-bec1-304207ea34a1">

---
